apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: hello-gorilla.example
      http:
        paths:
          - path: /serviceb
            pathType: Prefix
            backend:
              service:
                name: serviceb
                port:
                  number: 8000
    - host: hello-chi.example
      http:
        paths:
          - path: /servicea
            pathType: Prefix
            backend:
              service:
                name: servicea
                port:
                  number: 3000