[package]
name = "actix-web-websocket-demo"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "websocket-server"
path = "src/main.rs"

[dependencies]
actix-files = "0.6.9"
actix-web = "4.12.1"
actix-ws = "0.3.1"
env_logger = "0.11.8"
futures-util = "0.3.31"
log = "0.4.29"
tokio = { version = "1.49.0", features = ["full"] }
