receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp_http:
    traces_endpoint: "https://data-prepper:21890/ingest/otel-trace-pipeline/v1/traces"
    compression: gzip
    encoding: json
    tls:
      # TLS is enabled, but hostname/chain is not verified
      #insecure_skip_verify: true  
      ca_file: /usr/share/certs/otel-root-ca.pem
  # optional: see incoming/outgoing spans in logs
  debug:
    verbosity: basic

processors:
  batch: {}

extensions:
  health_check: {}

service:
  extensions: [health_check]
  #telemetry:
    #logs:
      #level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http, debug]