apiVersion: v1
kind: Service
metadata:
  name: my-multinode-cluster
spec:
  type: LoadBalancer
  selector:
    app: my-multinode-cluster
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
