---
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

# Configuration for memberlist client. Only applies if the selected kvstore is
# memberlist.
# 
# When a memberlist config with atleast 1 join_members is defined, kvstore of
# type memberlist is automatically selected for all the components that require
# a ring unless otherwise specified in the component's configuration section.
memberlist:
  join_members: ["read", "write", "backend"]
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s

# Configures the chunk index schema and where it is stored.
schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h
# Common configuration to be shared between multiple modules. If a more specific
# configuration is given in other sections, the related configuration within
# this section will be ignored.
common:
  path_prefix: /loki
  replication_factor: 1
  compactor_address: http://backend:3100
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true
  ring:
    kvstore:
      # Backend storage to use for the ring. Supported values are: consul,
      # etcd, inmemory, memberlist, multi.
      # CLI flag: -ingest-limits.store
      store: memberlist
# The ruler block configures the Loki ruler
ruler:
  storage:
    s3:
      bucketnames: loki-ruler

# The compactor block configures the compactor component, which compacts index
# shards for performance.
compactor:
  working_directory: /tmp/compactor